version: '3.8'

services:
  db:
    container_name: db
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: dev
      MONGO_INITDB_DATABASE: FinancialTracker
    volumes:
      - ./.mongodb:/data/db
    ports:
      - 27017:27017
    networks:
      - network-development

  mongo-express:
    container_name: mongo_express
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: dev
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: dev
      ME_CONFIG_MONGODB_SERVER: db
    ports:
      - 8081:8081
    depends_on:
      - db
    networks:
      - network-development

  # financial-tracker repo application
  financial-tracker:
    container_name: financial-tracker
    image: financial-tracker:1.0.0
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - .:/usr/financial-tracker
      - /usr/financial-tracker/node_modules
    networks:
      - network-development
    restart: unless-stopped

# Docker Networks
networks:
  network-development:
    driver: bridge